# Generated by Django 3.2.10 on 2022-05-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_id',
        ),
    ]
